### ISSUE TITLE
Container fails to start after latest docker build

### ISSUE THREAD

**Issue by depowell-D2L** [roribio/alpine-sqs#24] opened 2019-02-25 17:38 UTC
Hello,

This container was working perfectly until this morning. After the latest docker build on the morning of Feb 25, 2019 the container stopped working correctly. Logs show:

```
2019-02-25 17:23:51,778 INFO Included extra file "/etc/supervisor/conf.d/elasticmq.conf" during parsing
2019-02-25 17:23:51,778 INFO Included extra file "/etc/supervisor/conf.d/insight.conf" during parsing
2019-02-25 17:23:51,778 INFO Included extra file "/etc/supervisor/conf.d/sqs-init.conf" during parsing
2019-02-25 17:23:51,778 INFO Set uid to user 0 succeeded
2019-02-25 17:23:51,787 INFO RPC interface 'supervisor' initialized
2019-02-25 17:23:51,787 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-02-25 17:23:51,788 INFO supervisord started with pid 1
2019-02-25 17:23:52,791 INFO spawned: 'sqs-init' with pid 7
2019-02-25 17:23:52,793 INFO spawned: 'elasticmq' with pid 8
2019-02-25 17:23:52,794 INFO spawned: 'insight' with pid 9
cp: can't stat '/opt/custom/*.conf': No such file or directory
Error: Invalid or corrupt jarfile /opt/elasticmq-server.jar
2019-02-25 17:23:52,799 INFO exited: elasticmq (exit status 1; not expected)

> sqs-insight@0.3.0 start /opt/sqs-insight
> node index.js

Loading config file from "/opt/sqs-insight/lib/../config/config_local.json"
2019-02-25 17:23:53,799 INFO success: sqs-init entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-25 17:23:53,799 INFO success: insight entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-25 17:23:53,799 INFO exited: sqs-init (exit status 0; expected)
Unable to load queues for  undefined
2019-02-25 17:23:54,163 INFO spawned: 'elasticmq' with pid 34
Config contains 0 queues.
Error: Invalid or corrupt jarfile /opt/elasticmq-server.jar
2019-02-25 17:23:54,167 INFO exited: elasticmq (exit status 1; not expected)
listening on port 9325
2019-02-25 17:23:56,457 INFO spawned: 'elasticmq' with pid 35
Error: Invalid or corrupt jarfile /opt/elasticmq-server.jar
2019-02-25 17:23:56,464 INFO exited: elasticmq (exit status 1; not expected)
2019-02-25 17:23:59,469 INFO spawned: 'elasticmq' with pid 36
Error: Invalid or corrupt jarfile /opt/elasticmq-server.jar
2019-02-25 17:23:59,474 INFO exited: elasticmq (exit status 1; not expected)
2019-02-25 17:23:59,474 INFO gave up: elasticmq entered FATAL state, too many start retries too quickly
Unable to load queues for  undefined
```

**Comment by roribio** [comment] 2019-02-25 17:56
Hi,

Thank you for reporting this!

I don't know what could have caused this. There haven't been any changes on my side.

I'm looking at it now.

**Comment by kacper-kuczek** [comment] 2019-02-25 17:58
Hi repository is moved, I think the problem is
curl -s https://api.github.com/repos/adamw/elasticmq/releases/latest
response:
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/1951336/releases/latest",
  "documentation_url": "https://developer.github.com/v3/#http-redirects"
}

so should be:
curl -s https://api.github.com/repositories/1951336/releases/latest

**Comment by roribio** [comment] 2019-02-25 18:18
Nice catch @kacper-kuczek, that was the cause of the issue.

I've updated the Dockerfile and the image is being re-built now.

Thank you for your help @kacper-kuczek and @depowell-D2L!

**Comment by roribio** [comment] 2019-02-25 18:19
@depowell-D2L, once you confirm the issue has been resolved, I'll close this issue.

**Comment by depowell-D2L** [comment] 2019-02-25 18:23
It's working as expected again. Thanks for the super fast turn around.

**Comment by roribio** [comment] 2019-02-25 18:29
Awesome :D!

**Closed by roribio** 2019-02-25 18:29 UTC
Labels: bug, in progress
